function(CheckCompilerVersions)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "13")
            message(FATAL_ERROR "This project requires GCC version >= 13")
        endif()
    endif()

    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "16")
            message(FATAL_ERROR "This project requires Clang version >= 16")
        endif()
    endif()

    if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "19")
            message(FATAL_ERROR "This project requires MSVC versions >= 19")
        endif()
    endif()
endfunction()