#include "brasstacks/brasstacks.hpp"
#include "brasstacks/platform/win32/Win32ToBTXKeys.hpp"

namespace btx {

std::unordered_map<::USHORT, Keycode> const Win32ToBTXKeys::map {
    {   8u, KB_BACKSPACE },
    {   9u, KB_TAB },
    {  13u, KB_ENTER },
    {  19u, KB_PAUSE },
    {  20u, KB_CAPS_LOCK },
    {  27u, KB_ESCAPE },
    {  32u, KB_SPACE },
    {  33u, KB_PAGE_UP },
    {  34u, KB_PAGE_DOWN },
    {  35u, KB_END },
    {  36u, KB_HOME },
    {  37u, KB_LEFT },
    {  38u, KB_UP },
    {  39u, KB_RIGHT },
    {  40u, KB_DOWN },
    {  44u, KB_PRINT_SCREEN },
    {  45u, KB_INSERT },
    {  46u, KB_DELETE },
    {  48u, KB_0 },
    {  49u, KB_1 },
    {  50u, KB_2 },
    {  51u, KB_3 },
    {  52u, KB_4 },
    {  53u, KB_5 },
    {  54u, KB_6 },
    {  55u, KB_7 },
    {  56u, KB_8 },
    {  57u, KB_9 },

    {  KB_A, KB_A },
    {  KB_B, KB_B },
    {  KB_C, KB_C },
    {  KB_D, KB_D },
    {  KB_E, KB_E },
    {  KB_F, KB_F },
    {  KB_G, KB_G },
    {  KB_H, KB_H },
    {  KB_I, KB_I },
    {  KB_J, KB_J },
    {  KB_K, KB_K },
    {  KB_L, KB_L },
    {  KB_M, KB_M },
    {  KB_N, KB_N },
    {  KB_O, KB_O },
    {  KB_P, KB_P },
    {  KB_Q, KB_Q },
    {  KB_R, KB_R },
    {  KB_S, KB_S },
    {  KB_T, KB_T },
    {  KB_U, KB_U },
    {  KB_V, KB_V },
    {  KB_W, KB_W },
    {  KB_X, KB_X },
    {  KB_Y, KB_Y },
    {  KB_Z, KB_Z },

    {  93u, KB_MENU },
    {  96u, KB_NP_0 },
    {  97u, KB_NP_1 },
    {  98u, KB_NP_2 },
    {  99u, KB_NP_3 },
    { 100u, KB_NP_4 },
    { 101u, KB_NP_5 },
    { 102u, KB_NP_6 },
    { 103u, KB_NP_7 },
    { 104u, KB_NP_8 },
    { 105u, KB_NP_9 },
    { 106u, KB_NP_MULTIPLY },
    { 107u, KB_NP_ADD },
    { 109u, KB_NP_SUBTRACT },
    { 110u, KB_NP_DECIMAL },
    { 111u, KB_NP_DIVIDE },
    { 112u, KB_F1 },
    { 113u, KB_F2 },
    { 114u, KB_F3 },
    { 115u, KB_F4 },
    { 116u, KB_F5 },
    { 117u, KB_F6 },
    { 118u, KB_F7 },
    { 119u, KB_F8 },
    { 120u, KB_F9 },
    { 121u, KB_F10 },
    { 122u, KB_F11 },
    { 123u, KB_F12 },
    { 144u, KB_NUM_LOCK },
    { 145u, KB_SCROLL_LOCK },
    { 160u, KB_LEFT_SHIFT },
    { 161u, KB_RIGHT_SHIFT },
    { 186u, KB_SEMICOLON },
    { 187u, KB_EQUAL },
    { 188u, KB_COMMA },
    { 189u, KB_MINUS },
    { 190u, KB_PERIOD },
    { 191u, KB_FRONT_SLASH },
    { 192u, KB_GRAVE },
    { 219u, KB_LEFT_BRACKET },
    { 221u, KB_RIGHT_BRACKET },
    { 220u, KB_BACK_SLASH },
    { 222u, KB_APOSTROPHE },
    { 335u, KB_NP_ENTER },

    { KB_LEFT_CTRL,   KB_LEFT_CTRL },
    { KB_RIGHT_CTRL,  KB_RIGHT_CTRL },
    { KB_LEFT_SUPER,  KB_LEFT_SUPER },
    { KB_RIGHT_SUPER, KB_RIGHT_SUPER },
    { KB_LEFT_ALT,    KB_LEFT_ALT },
    { KB_RIGHT_ALT,   KB_RIGHT_ALT },
};

} // namespace btx