#ifndef BRASSTACKS_ECS_COMPONENTS_CAMERACOMPONENT_HPP
#define BRASSTACKS_ECS_COMPONENTS_CAMERACOMPONENT_HPP

namespace btx {

struct CameraComponent { };

} // namespace btx

#endif // BRASSTACKS_ECS_COMPONENTS_CAMERACOMPONENT_HPP