#ifndef BRASSTACKS_ECS_COMPONENTS_CUBECOMP_HPP
#define BRASSTACKS_ECS_COMPONENTS_CUBECOMP_HPP

namespace btx {

struct CubeComp { };

} // namespace btx

#endif // BRASSTACKS_ECS_COMPONENTS_CUBECOMP_HPP