#ifndef BRASSTACKS_ECS_COMPONENTS_CUBECOMPONENT_HPP
#define BRASSTACKS_ECS_COMPONENTS_CUBECOMPONENT_HPP

namespace btx {

struct CubeComponent { };

} // namespace btx

#endif // BRASSTACKS_ECS_COMPONENTS_CUBECOMPONENT_HPP