#ifndef BRASSTACKS_ASSETLIBRARIES_SHADERLIBRARY_HPP
#define BRASSTACKS_ASSETLIBRARIES_SHADERLIBRARY_HPP

namespace btx {

class ShaderLibrary {

};

} // namespace btx

#endif // BRASSTACKS_ASSETLIBRARIES_SHADERLIBRARY_HPP