#include "brasstacks/platform/input/GLFWToBTXKeys.hpp"

namespace btx {

GLFWToBTXKeys::GLFWToBTXKeys() :
    _map {

        { GLFW_KEY_SPACE              , BTX_KB_SPACE },
        { GLFW_KEY_APOSTROPHE         , BTX_KB_APOSTROPHE },
        { GLFW_KEY_COMMA              , BTX_KB_COMMA },
        { GLFW_KEY_MINUS              , BTX_KB_MINUS },
        { GLFW_KEY_PERIOD             , BTX_KB_PERIOD },
        { GLFW_KEY_SLASH              , BTX_KB_FRONT_SLASH },
        { GLFW_KEY_0                  , BTX_KB_0 },
        { GLFW_KEY_1                  , BTX_KB_1 },
        { GLFW_KEY_2                  , BTX_KB_2 },
        { GLFW_KEY_3                  , BTX_KB_3 },
        { GLFW_KEY_4                  , BTX_KB_4 },
        { GLFW_KEY_5                  , BTX_KB_5 },
        { GLFW_KEY_6                  , BTX_KB_6 },
        { GLFW_KEY_7                  , BTX_KB_7 },
        { GLFW_KEY_8                  , BTX_KB_8 },
        { GLFW_KEY_9                  , BTX_KB_9 },
        { GLFW_KEY_SEMICOLON          , BTX_KB_SEMICOLON },
        { GLFW_KEY_EQUAL              , BTX_KB_EQUAL },
        { GLFW_KEY_A                  , BTX_KB_A },
        { GLFW_KEY_B                  , BTX_KB_B },
        { GLFW_KEY_C                  , BTX_KB_C },
        { GLFW_KEY_D                  , BTX_KB_D },
        { GLFW_KEY_E                  , BTX_KB_E },
        { GLFW_KEY_F                  , BTX_KB_F },
        { GLFW_KEY_G                  , BTX_KB_G },
        { GLFW_KEY_H                  , BTX_KB_H },
        { GLFW_KEY_I                  , BTX_KB_I },
        { GLFW_KEY_J                  , BTX_KB_J },
        { GLFW_KEY_K                  , BTX_KB_K },
        { GLFW_KEY_L                  , BTX_KB_L },
        { GLFW_KEY_M                  , BTX_KB_M },
        { GLFW_KEY_N                  , BTX_KB_N },
        { GLFW_KEY_O                  , BTX_KB_O },
        { GLFW_KEY_P                  , BTX_KB_P },
        { GLFW_KEY_Q                  , BTX_KB_Q },
        { GLFW_KEY_R                  , BTX_KB_R },
        { GLFW_KEY_S                  , BTX_KB_S },
        { GLFW_KEY_T                  , BTX_KB_T },
        { GLFW_KEY_U                  , BTX_KB_U },
        { GLFW_KEY_V                  , BTX_KB_V },
        { GLFW_KEY_W                  , BTX_KB_W },
        { GLFW_KEY_X                  , BTX_KB_X },
        { GLFW_KEY_Y                  , BTX_KB_Y },
        { GLFW_KEY_Z                  , BTX_KB_Z },
        { GLFW_KEY_LEFT_BRACKET       , BTX_KB_LEFT_BRACKET },
        { GLFW_KEY_BACKSLASH          , BTX_KB_BACK_SLASH },
        { GLFW_KEY_RIGHT_BRACKET      , BTX_KB_RIGHT_BRACKET },
        { GLFW_KEY_GRAVE_ACCENT       , BTX_KB_GRAVE },

        { GLFW_KEY_ESCAPE             , BTX_KB_ESCAPE },
        { GLFW_KEY_ENTER              , BTX_KB_ENTER },
        { GLFW_KEY_TAB                , BTX_KB_TAB },
        { GLFW_KEY_BACKSPACE          , BTX_KB_BACKSPACE },
        { GLFW_KEY_INSERT             , BTX_KB_INSERT },
        { GLFW_KEY_DELETE             , BTX_KB_DELETE },
        { GLFW_KEY_RIGHT              , BTX_KB_RIGHT },
        { GLFW_KEY_LEFT               , BTX_KB_LEFT },
        { GLFW_KEY_DOWN               , BTX_KB_DOWN },
        { GLFW_KEY_UP                 , BTX_KB_UP },
        { GLFW_KEY_PAGE_UP            , BTX_KB_PAGE_UP },
        { GLFW_KEY_PAGE_DOWN          , BTX_KB_PAGE_DOWN },
        { GLFW_KEY_HOME               , BTX_KB_HOME },
        { GLFW_KEY_END                , BTX_KB_END },
        { GLFW_KEY_CAPS_LOCK          , BTX_KB_CAPS_LOCK },
        { GLFW_KEY_SCROLL_LOCK        , BTX_KB_SCROLL_LOCK },
        { GLFW_KEY_NUM_LOCK           , BTX_KB_NUM_LOCK },
        { GLFW_KEY_PRINT_SCREEN       , BTX_KB_PRINT_SCREEN },
        { GLFW_KEY_PAUSE              , BTX_KB_PAUSE },
        { GLFW_KEY_F1                 , BTX_KB_F1 },
        { GLFW_KEY_F2                 , BTX_KB_F2 },
        { GLFW_KEY_F3                 , BTX_KB_F3 },
        { GLFW_KEY_F4                 , BTX_KB_F4 },
        { GLFW_KEY_F5                 , BTX_KB_F5 },
        { GLFW_KEY_F6                 , BTX_KB_F6 },
        { GLFW_KEY_F7                 , BTX_KB_F7 },
        { GLFW_KEY_F8                 , BTX_KB_F8 },
        { GLFW_KEY_F9                 , BTX_KB_F9 },
        { GLFW_KEY_F10                , BTX_KB_F10 },
        { GLFW_KEY_F11                , BTX_KB_F11 },
        { GLFW_KEY_F12                , BTX_KB_F12 },
        { GLFW_KEY_KP_0               , BTX_KB_NP_0 },
        { GLFW_KEY_KP_1               , BTX_KB_NP_1 },
        { GLFW_KEY_KP_2               , BTX_KB_NP_2 },
        { GLFW_KEY_KP_3               , BTX_KB_NP_3 },
        { GLFW_KEY_KP_4               , BTX_KB_NP_4 },
        { GLFW_KEY_KP_5               , BTX_KB_NP_5 },
        { GLFW_KEY_KP_6               , BTX_KB_NP_6 },
        { GLFW_KEY_KP_7               , BTX_KB_NP_7 },
        { GLFW_KEY_KP_8               , BTX_KB_NP_8 },
        { GLFW_KEY_KP_9               , BTX_KB_NP_9 },
        { GLFW_KEY_KP_DECIMAL         , BTX_KB_NP_DECIMAL },
        { GLFW_KEY_KP_DIVIDE          , BTX_KB_NP_DIVIDE },
        { GLFW_KEY_KP_MULTIPLY        , BTX_KB_NP_MULTIPLY },
        { GLFW_KEY_KP_SUBTRACT        , BTX_KB_NP_SUBTRACT },
        { GLFW_KEY_KP_ADD             , BTX_KB_NP_ADD },
        { GLFW_KEY_KP_ENTER           , BTX_KB_NP_ENTER },
        { GLFW_KEY_KP_EQUAL           , BTX_KB_NP_EQUAL },
        { GLFW_KEY_LEFT_SHIFT         , BTX_KB_LEFT_SHIFT },
        { GLFW_KEY_LEFT_CONTROL       , BTX_KB_LEFT_CTRL },
        { GLFW_KEY_LEFT_ALT           , BTX_KB_LEFT_ALT },
        { GLFW_KEY_LEFT_SUPER         , BTX_KB_LEFT_SUPER },
        { GLFW_KEY_RIGHT_SHIFT        , BTX_KB_RIGHT_SHIFT },
        { GLFW_KEY_RIGHT_CONTROL      , BTX_KB_RIGHT_CTRL },
        { GLFW_KEY_RIGHT_ALT          , BTX_KB_RIGHT_ALT },
        { GLFW_KEY_RIGHT_SUPER        , BTX_KB_RIGHT_SUPER },
        { GLFW_KEY_MENU               , BTX_KB_MENU },

        { GLFW_MOUSE_BUTTON_1         , BTX_MB_LEFT },
        { GLFW_MOUSE_BUTTON_2         , BTX_MB_RIGHT },
        { GLFW_MOUSE_BUTTON_3         , BTX_MB_MIDDLE },
    }
{ }

} // namespace btx