function(set_target_arch)
    # For x86_64, target Haswell/Excavator or newer
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|amd64|AMD64")
            add_compile_options("-march=x86-64-v3")
        else()
            message(WARNING "Unknown CPU architecture ${CMAKE_SYSTEM_PROCESSOR} not targeted.")
        endif()
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "AMD64")
            add_compile_options("/arch:AVX2")
            else()
                message(WARNING "Unknown CPU architecture ${CMAKE_SYSTEM_PROCESSOR} not targeted.")
        endif()
    endif()
endfunction()